# Generated by Django 3.2.4 on 2021-06-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('edition', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.book')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_division', models.CharField(max_length=50)),
                ('sub_division', models.CharField(max_length=50)),
                ('sub_sub_division', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='PublisherBookMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.book')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField()),
                ('date_of_return', models.DateField(null=True)),
                ('copy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.copy')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='FineCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=4)),
                ('payment_mode', models.CharField(max_length=20)),
                ('lease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.lease')),
            ],
        ),
        migrations.CreateModel(
            name='CopyLocationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.copy')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.location')),
            ],
        ),
        migrations.AddField(
            model_name='copy',
            name='lease_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dlm.lease'),
        ),
        migrations.CreateModel(
            name='CategoryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_count', models.IntegerField()),
                ('lease_days', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fine_rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ebook_access', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.category')),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.author')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlm.booktype'),
        ),
    ]
