# Generated by Django 3.2.4 on 2021-06-21 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1000)),
                ('mobile', models.CharField(max_length=50)),
                ('photo', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLibraryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('libraryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.library')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userdata')),
            ],
        ),
    ]
